# Generated by Django 3.2 on 2021-10-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingnetprice',
            name='net_shipping_price',
            field=models.FloatField(verbose_name='cost'),
        ),
    ]
