# Generated by Django 3.2 on 2021-08-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
