# Generated by Django 3.2 on 2021-08-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='name2',
            new_name='second_name',
        ),
    ]
