# Generated by Django 3.2 on 2021-10-11 15:20

import customization.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCopy', models.BooleanField(default=False)),
                ('inCart', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'custompack',
            },
        ),
        migrations.CreateModel(
            name='CustomPackSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('image_price', models.PositiveIntegerField()),
                ('maxNb_Of_images', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomPackUserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=customization.models.upload_to, verbose_name='Image')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=3, max_digits=10)),
                ('custompack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='customization.custompack')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPackArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('custompack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.custompack')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.article')),
            ],
            options={
                'verbose_name': 'packarticle',
            },
        ),
    ]
