# Generated by Django 3.2 on 2021-10-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='boxe',
        ),
    ]
