# Generated by Django 3.2 on 2021-08-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayementMode',
        ),
    ]
