# Generated by Django 3.2 on 2021-10-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='category')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': '3.Article Categorie',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=30)),
                ('articlecategories', models.ManyToManyField(blank=True, to='categories.ArticleCategory')),
            ],
            options={
                'verbose_name': '7.Category filter',
            },
        ),
        migrations.CreateModel(
            name='PackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('is_main', models.BooleanField(default=False, verbose_name='Principal category')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(blank=True, max_length=30)),
                ('articles_categories', models.ManyToManyField(blank=True, to='categories.ArticleCategory')),
            ],
            options={
                'verbose_name': '2.Pack Categorie',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('is_main', models.BooleanField(default=False, verbose_name='Principal category')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': '1.Product Categorie',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ManyToManyField(blank=True, to='categories.Filter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('productcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.productcategory')),
            ],
            options={
                'verbose_name': '5.Product categorie Item',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='items',
            field=models.ManyToManyField(through='categories.ProductCategoryItem', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.productcategory'),
        ),
        migrations.CreateModel(
            name='PackCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.ManyToManyField(blank=True, to='categories.Filter')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pack')),
                ('packcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.packcategory')),
            ],
            options={
                'verbose_name': '6.Pack categorie Item',
            },
        ),
        migrations.AddField(
            model_name='packcategory',
            name='items',
            field=models.ManyToManyField(through='categories.PackCategoryItem', to='products.Pack'),
        ),
        migrations.AddField(
            model_name='packcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.packcategory', verbose_name='Child of '),
        ),
        migrations.AddField(
            model_name='filter',
            name='packcategories',
            field=models.ManyToManyField(blank=True, to='categories.PackCategory'),
        ),
        migrations.AddField(
            model_name='filter',
            name='productcaegories',
            field=models.ManyToManyField(blank=True, to='categories.ProductCategory'),
        ),
        migrations.CreateModel(
            name='ArticleCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.article')),
                ('articlecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.articlecategory')),
                ('filter', models.ManyToManyField(blank=True, to='categories.Filter')),
            ],
            options={
                'verbose_name': '6.Article categorie Item',
            },
        ),
    ]
