# Generated by Django 3.2 on 2021-10-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
