# Generated by Django 3.2 on 2021-10-11 15:20

from django.db import migrations, models
import django.db.models.deletion
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('categories', '0001_initial'),
        ('customization', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingBoxImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=media.models.upload_to, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='delivery.shippingbox')),
            ],
            options={
                'verbose_name': 'shippingbox',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=media.models.upload_to, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'productimage',
            },
        ),
        migrations.CreateModel(
            name='PackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.BooleanField(default=False)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=media.models.upload_to, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.pack')),
            ],
            options={
                'verbose_name': 'packimage',
            },
        ),
        migrations.CreateModel(
            name='CustomPackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=media.models.upload_to, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='customization.custompack')),
            ],
            options={
                'verbose_name': 'custompackimage',
            },
        ),
        migrations.CreateModel(
            name='BoxeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=media.models.upload_to, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.boxe')),
            ],
            options={
                'verbose_name': 'boxeimage',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=media.models.upload_to, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.article')),
            ],
            options={
                'verbose_name': 'articleimage',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=media.models.upload_to, verbose_name='Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='categories.articlecategory')),
            ],
            options={
                'verbose_name': 'articlecategoryimage',
            },
        ),
    ]
