# Generated by Django 3.2 on 2021-10-11 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Préparation pour la livraison'), ('shipping', 'En cours de livraison'), ('shipped', 'Livrée'), ('refunded', 'Retournéé')], default='created', max_length=120)),
                ('subject', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='subject')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Préparation pour la livraison'), ('shipping', 'En cours de livraison'), ('shipped', 'Livrée'), ('refunded', 'Retournéé')], default='created', max_length=120)),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 10, 11, 15, 20, 37, 351593, tzinfo=utc))),
                ('shipping_total_price', models.FloatField(blank=True, null=True)),
                ('shipping_time', models.IntegerField(blank=True, null=True)),
                ('order_total', models.FloatField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('payment_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentmode')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
