# Generated by Django 3.2 on 2021-08-17 21:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('shipping', 'Shipping'), ('shipped', 'Shipped'), ('refunded', 'Refunded')], default='created', max_length=120)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipping_total_price', models.DecimalField(blank=True, decimal_places=2, default=5.99, max_digits=50)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
