# Generated by Django 3.2 on 2021-10-28 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderemail',
            name='status',
        ),
        migrations.AddField(
            model_name='orderemail',
            name='order_status',
            field=models.CharField(choices=[('created', 'Préparation pour la livraison'), ('shipping', 'En cours de livraison'), ('shipped', 'Livrée'), ('refunded', 'Retournéé')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='orderemail',
            name='send_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderemail',
            name='send_is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderemail',
            name='send_orderSubtotal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderemail',
            name='send_paymentMode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderemail',
            name='send_shippingAddress',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderemail',
            name='send_shippingCost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderemail',
            name='send_shippingMode',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 9, 34, 56, 918236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Préparation pour la livraison'), ('shipping', 'En cours de livraison'), ('shipped', 'Livrée'), ('refunded', 'Retournéé')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderemail',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
