# Generated by Django 3.2 on 2021-10-28 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20211028_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEmailz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=200)),
                ('order_status', models.CharField(choices=[('created', 'Préparation pour la livraison'), ('shipping', 'En cours de livraison'), ('shipped', 'Livrée'), ('refunded', 'Retournéé')], max_length=30, null=True)),
                ('send_id', models.BooleanField(default=True)),
                ('send_orderSubtotal', models.BooleanField(default=True)),
                ('send_shippingCost', models.BooleanField(default=True)),
                ('send_shippingAddress', models.BooleanField(default=True)),
                ('send_shippingMode', models.BooleanField(default=True)),
                ('send_paymentMode', models.BooleanField(default=True)),
                ('send_is_paid', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 9, 37, 31, 488412, tzinfo=utc)),
        ),
    ]
