# Generated by Django 3.2 on 2021-10-28 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20211028_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 20, 52, 40, 598270, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderemail',
            name='subject',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderemail',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
