# Generated by Django 3.2 on 2021-10-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211012_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
