# Generated by Django 3.2 on 2021-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211012_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'ordering': ['orders'], 'verbose_name': 'pack'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['orders'], 'verbose_name': 'product'},
        ),
        migrations.AddField(
            model_name='pack',
            name='promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='promo_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
