# Generated by Django 3.2 on 2021-10-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211019_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='features',
        ),
        migrations.AddField(
            model_name='pack',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductFeature'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='products.ProductFeature'),
        ),
    ]
